name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpass
          MYSQL_DATABASE: app
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-restful pymysql python-dotenv
    - name: Test with SQLite
      env:
        DB_TYPE: sqlite
        SQLITE_DB: app.db
      run: |
        python -m unittest discover -s test
    - name: Download wait-for-it
      run: curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
    - name: Wait for MySQL
      run: bash wait-for-it.sh 127.0.0.1:3306 -t 30
    - name: Test with MySQL
      env:
        DB_TYPE: mysql
        MYSQL_HOST: 127.0.0.1
        MYSQL_USER: root
        MYSQL_PASSWORD: testpass
        MYSQL_DATABASE: app
        MYSQL_CHARSET: utf8mb4
      run: |
        python -m unittest discover -s test
